---
- hosts: all
  become: yes
  tasks:
    - name: Create the receptor user
      user:
        name: "{{ receptor_user }}"
        shell: /bin/bash
    - import_role:
        name: ansible.receptor.podman
    - import_role:
        name: ansible.receptor.setup
